/*
 * Items
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Ignore;


/**
 * API tests for Api
 */
@Ignore
public class ApiTest {

    private final Api api;

    public ApiTest(Api api) {
        this.api = api;
    }


}
